version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:8080"
    links:
      - mongo
    image: aakashsigdel/coffeeapi_web
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
    image: aakashsigdel/coffeeapi_mongo-seed
  mongo:
    image: mongo
    ports:
      - "27017:27017"
