version: "2"
services:
  web:
    build: .
    ports:
      - "4000:8080"
    links:
      - mongo
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
